name: RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Install Pinggy CLI
        shell: powershell
        run: |
          npm install -g pinggy

      - name: Start Pinggy TCP Tunnel
        shell: powershell
        run: |
          pinggy --token "${{ secrets.PINGGY_TOKEN }}" --type tcp -l 3389
